
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'LETRAS NUMEROScurp : LETRAS LETRAS LETRAS LETRAS NUMEROS NUMEROS NUMEROS NUMEROS NUMEROS NUMEROS LETRAS LETRAS LETRAS LETRAS LETRAS NUMEROS'
    
_lr_action_items = {'LETRAS':([0,2,3,4,11,12,13,14,15,],[2,3,4,5,12,13,14,15,16,]),'$end':([1,17,],[0,-1,]),'NUMEROS':([5,6,7,8,9,10,16,],[6,7,8,9,10,11,17,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'curp':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> curp","S'",1,None,None,None),
  ('curp -> LETRAS LETRAS LETRAS LETRAS NUMEROS NUMEROS NUMEROS NUMEROS NUMEROS NUMEROS LETRAS LETRAS LETRAS LETRAS LETRAS NUMEROS','curp',16,'p_curp','app.py',27),
]
